### ISSUE TITLE
License of the software

### ISSUE THREAD

**Issue by habernal** [duongphuhiep/justext#1]
Hi, I'd like to ask under which license is this software available.

We adapted few parts into our processing pipeline in DKPro C4Corpus Tools (https://github.com/dkpro/dkpro-c4corpus), which we would like to release under ASL license, but we would like to make it clear. The best case would be if you release that under ASL or similar.

Thanks,

Ivan

**Comment by duongphuhiep** [comment]
I attached the Apache License 2.0 to this repository.

Thanks

Hiep

**Comment by habernal** [comment]
Great, thanks!
